fixed ESLint error src/pages/favorites-screen/favorites-screen.tsx(16,19): error TS2741: Property 'pageName' is missing in type '{}' but required in type 'LogoProps'.